spring:
  application:
    name: FinallyPro2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finallypro?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&serverTimezone=Asia/Shanghai
    username: root
    password: "123"


  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  jackson:
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    database: 0
  servlet:
    multipart:
      max-file-size: 100MB


server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.finallypro2.POJO
#  configuration:
#    map-underscore-to-camel-case: true